---
ips:
 - input1 #prefix original file name input1.R1.fastq.gz input1.R2.fastq.gz
 - input2
 - input3
controls:
 - control1
 - control2

genome: path/to/bwa/index/hg19
chrom: path/to/chrom/file/hg19.chrom.sizes
sponge_flag: false
sponges: path/to/sponges/names
path: /home/user/git/psychip_snakemake/common
macs2:/path/to/macs2
macs_g: hs
paired: true
matching: false
sort: sort #or path to the update version
shuf: shuf #or path to the update version
