ips:
 - HBCC_ACC_340_A
 - HBCC_ACC_378_A
 - HBCC_ACC_362_A
 - HBCC_ACC_358_A
 - HBCC_ACC_344_A
 - HBCC_ACC_352_A
 - HBCC_ACC_350_A
 - HBCC_ACC_354_A
 - HBCC_ACC_346_A
 - HBCC_ACC_376_A
 - HBCC_ACC_360_A
 - HBCC_ACC_374_A
 - HBCC_ACC_370_C
 - HBCC_ACC_342_A
controls:
 - HBCC_ACC_385_Pos_IN
 - HBCC_ACC_346_Pos_IN
 - HBCC_ACC_370_Pos_IN
 - HBCC_ACC_342_Pos_IN

genome: hg19/hg19_with_sponges.fa
chrom: shared/hg19.chrom.sizes
sponge_flag: true
sponges: shared/GRCh37_sponge.names
path: psychip_snakemake/common
macs2: /home/mp63w/bin/MACS_weng/bin/macs2
macs_g: hs
paired: true
matching: false
sort: Programs/bin/sort
split: Programs/bin/split
tf: false
